game:
  type: multiple_choice
  name: צלילי אנגלית
  description: תרגול זיהוי מילות אנגלית לפי צליל
  showTimer: false
  categories:
    English_Sound_Words:
      name: צלילי אנגלית
  multipleChoice:
    enabled: false
    checked: true
    choiceCount: 4
  scoring:
    trackTime: true
    trackAccuracy: true
  exerciseCount: 100
  content:
    - answer: Dog דוֹג
      choices:
      - Cat קַט
      - Horse הוֹרְס
      - Cow קוֹאוּ
      question: כֶּלֶב
    - answer: Cat קַט
      choices:
      - Horse הוֹרְס
      - Cow קוֹאוּ
      - Dog דוֹג
      question: חָתוּל
    - answer: Horse הוֹרְס
      choices:
      - Cow קוֹאוּ
      - Cat קַט
      - Bird בּרד
      question: סוּס
    - answer: Cow קוֹאוּ
      choices:
      - Dog דוֹג
      - Cat קַט
      - Bird בּרד
      question: פָּרָה
    - answer: Bird בּרד
      choices:
      - Dog דוֹג
      - Cat קַט
      - Cow קוֹאוּ
      question: צִפּוֹר
    - answer: Red רֶד
      choices:
      - Yellow יֶלוּ
      - Blue בּלוּ
      - Green גְּרִין
      question: אָדוֹם
    - answer: Blue בּלוּ
      choices:
      - Yellow יֶלוּ
      - Black בּלָאק
      - Green גְּרִין
      question: כָּחֹל
    - answer: Green גְּרִין
      choices:
      - Red רֶד
      - Blue בּלוּ
      - Black בּלָאק
      question: יָרוֹק
    - answer: Yellow יֶלוּ
      choices:
      - Green גְּרִין
      - Black בּלָאק
      - Red רֶד
      question: צָהֹב
    - answer: Black בּלָאק
      choices:
      - Blue בּלוּ
      - Red רֶד
      - Green גְּרִין
      question: שָׁחוֹר
    - answer: One וואן
      choices:
      - Three תְּרִי
      - Two טוּ
      - Five פַיְב
      question: אֶחָד
    - answer: Two טוּ
      choices:
      - One וואן
      - Five פַיְב
      - Four פוֹר
      question: שְׁתַּיִם
    - answer: Three תְּרִי
      choices:
      - One וואן
      - Five פַיְב
      - Four פוֹר
      question: שָׁלֹשׁ
    - answer: Four פוֹר
      choices:
      - Five פַיְב
      - Three תְּרִי
      - Two טוּ
      question: אַרְבַּע
    - answer: Five פַיְב
      choices:
      - Four פוֹר
      - One וואן
      - Three תְּרִי
      question: חָמֵשׁ
    - answer: Father פָאדֶר
      choices:
      - Mother מָאדֶר
      - Brother בּרָדֶר
      - Grandfather גְרָאנְדְפָאדֶר
      question: אַבָּא
    - answer: Mother מָאדֶר
      choices:
      - Grandfather גְרָאנְדְפָאדֶר
      - Brother בּרָדֶר
      - Father פָאדֶר
      question: אִמָּא
    - answer: Brother בּרָדֶר
      choices:
      - Grandfather גְרָאנְדְפָאדֶר
      - Father פָאדֶר
      - Sister סִיסְטֶר
      question: אָח
    - answer: Sister סִיסְטֶר
      choices:
      - Brother בּרָדֶר
      - Mother מָאדֶר
      - Grandfather גְרָאנְדְפָאדֶר
      question: אָחוֹת
    - answer: Grandfather גְרָאנְדְפָאדֶר
      choices:
      - Mother מָאדֶר
      - Brother בּרָדֶר
      - Father פָאדֶר
      question: סַבָּא
    - answer: Bread בּרֶד
      choices:
      - Apple אָפֶּל
      - Milk מִלְק
      - Banana בָּנָנָה
      question: לֶחֶם
    - answer: Milk מִלְק
      choices:
      - Banana בָּנָנָה
      - Bread בּרֶד
      - Apple אָפֶּל
      question: חָלָב
    - answer: Apple אָפֶּל
      choices:
      - Banana בָּנָנָה
      - Milk מִלְק
      - Bread בּרֶד
      question: תַּפּוּחַ
    - answer: Banana בָּנָנָה
      choices:
      - Cake כֵּיק
      - Milk מִלְק
      - Bread בּרֶד
      question: בָּנָנָה
    - answer: Cake כֵּיק
      choices:
      - Bread בּרֶד
      - Milk מִלְק
      - Apple אָפֶּל
      question: עוּגָה
