Arithmetic_Calculations_and_Missing_Number_Equations:
  - "4 + 7 = ___"
  - "___ − 5 = 9"
  - "3 × 2 = ___"
  - "12 ÷ 3 = ___"
  - "___ + 8 = 14"
  - "9 − ___ = 2"
  - "5 + ___ = 11"
  - "16 ÷ 4 = ___"
  - "7 + 6 = ___"
  - "___ × 2 = 18"
  - "10 − 4 = ___"
  - "9 + ___ = 15"
  - "___ − 3 = 6"
  - "4 × ___ = 16"
  - "12 − 7 = ___"
  - "___ + 5 = 13"
  - "18 ÷ ___ = 3"
  - "6 + 9 = ___"
  - "___ − 8 = 4"
  - "3 × ___ = 12"
  - "___ + 6 = 9"
  - "15 ÷ 5 = ___"
  - "7 + ___ = 12"
  - "___ − 2 = 5"
  - "8 × ___ = 24"
  - "11 + 4 = ___"
  - "___ + 9 = 18"
  - "14 − ___ = 6"
  - "___ ÷ 2 = 7"
  - "4 + ___ = 10"
  - "9 × 2 = ___"
  - "___ − 1 = 12"
  - "18 − ___ = 11"
  - "___ × 3 = 15"
  - "5 + 8 = ___"
  - "___ + 2 = 17"
  - "20 ÷ ___ = 4"
  - "___ − 9 = 1"
  - "6 × ___ = 18"
  - "___ + 7 = 13"
  - "10 + 5 = ___"
  - "___ − 4 = 10"
  - "3 × 4 = ___"
  - "___ ÷ 3 = 5"
  - "13 − ___ = 7"
  - "___ + 6 = 20"
  - "8 × 2 = ___"
  - "___ − 5 = 3"
  - "16 ÷ 2 = ___"
  - "___ + 4 = 12"
  - "27 + 36 = ___"
  - "___ − 19 = 43"
  - "8 × 7 = ___"
  - "64 ÷ 8 = ___"
  - "___ + 58 = 97"
  - "72 − ___ = 38"
  - "9 × ___ = 81"
  - "48 ÷ ___ = 6"
  - "35 + 29 = ___"
  - "___ − 27 = 65"
  - "6 × 12 = ___"
  - "84 ÷ 7 = ___"
  - "___ + 17 = 100"
  - "90 − ___ = 24"
  - "___ × 9 = 63"
  - "54 ÷ ___ = 9"
  - "18 + 47 = ___"
  - "___ − 33 = 22"
  - "7 × 8 = ___"
  - "96 ÷ 12 = ___"
  - "___ + 43 = 86"
  - "99 − ___ = 45"
  - "5 × ___ = 45"
  - "60 ÷ ___ = 10"
  - "42 + 28 = ___"
  - "___ − 14 = 59"
  - "11 × 5 = ___"
  - "81 ÷ 9 = ___"
  - "___ + 34 = 79"
  - "70 − ___ = 18"
  - "___ × 6 = 48"
  - "63 ÷ ___ = 7"
  - "29 + 46 = ___"
  - "___ − 41 = 37"
  - "4 × 13 = ___"
  - "88 ÷ 11 = ___"
  - "___ + 62 = 95"
  - "100 − ___ = 36"
  - "___ × 8 = 72"
  - "56 ÷ ___ = 7"
  - "24 + 57 = ___"
  - "___ − 28 = 49"
  - "12 × 4 = ___"
  - "96 ÷ 16 = ___"
  - "___ + 31 = 68"
  - "85 − ___ = 27"
  - "___ × 7 = 56"
  - "72 ÷ ___ = 9"
  - "43 + 39 = ___"
  - "___ − 44 = 30"

One_Step_Arithmetic_Word_Problems:
  - "לנועה היו 6 בלונים והיא קיבלה עוד 5 בלונים מחברתה. כמה בלונים יש לה עכשיו?"
  - "אבא נתן לעומר 10 שקלים. עומר קנה גלידה ב־4 שקלים. כמה כסף נשאר לעומר?"
  - "בכיתה יש 8 בנים ו־11 בנות. כמה תלמידים יש בכיתה בסך הכול?"
  - "ליוסי 12 תפוחים. הוא חילק אותם שווה בשווה בין שני חברים. כמה תפוחים קיבל כל חבר?"
  - "במדף יש 9 ספרים. הוסיפו למדף עוד 7 ספרים. כמה ספרים יש כעת על המדף?"
  - "טל נסע 14 קילומטר בבוקר ועוד 6 קילומטר אחר-הצהריים. כמה קילומטרים נסע טל באותו יום?"
  - "לדנה היו 15 מדבקות. היא נתנה 6 מדבקות לאחיה. כמה מדבקות נשארו לדנה?"
  - "בסל היו 18 תפוזים. אמא השתמשה ב־8 תפוזים למיץ. כמה תפוזים נשארו בסל?"
  - "בחנות צעצועים נמכרו 20 כדורים. 5 מהם היו כדורי כדורסל והשאר כדורי רגל. כמה כדורי רגל נמכרו?"
  - "4 ילדים קיבלו במתנה 3 עוגיות לכל אחד. כמה עוגיות חולקו בסך הכול?"
  - "במרוץ, דנה רצה 7 סיבובים וירון רץ 9 סיבובים. בכמה סיבובים ירון הקדים את דנה?"
  - "למיכל היו 13 גולות. היא קיבלה עוד 4 גולות. כמה גולות יש לה היום?"
  - "בשיעור ציור השתמשו ב-16 עפרונות צבעוניים. 6 נשברו. כמה עפרונות נשארו תקינים?"
  - "על העץ צפו 12 ציפורים. 5 מהן עפו. כמה ציפורים נשארו על העץ?"
  - "איתן חסך 30 שקלים וקנה צעצוע ב-18 שקלים. כמה כסף נשאר לו?"
  - "לירון 8 סוכריות. היא חילקה אותן שווה בשווה בין 2 אחיה. כמה סוכריות קיבל כל אח?"
  - "בכיתה יש 24 כיסאות. אם מסדרים אותם ב-6 שורות שוות, כמה כיסאות יש בכל שורה?"
  - "לגאיה 9 עפרונות. היא קיבלה עוד 7. כמה עפרונות יש לה?"
  - "ברפת היו 14 פרות. נוספו עוד 3 פרות חדשות. כמה פרות יש כעת ברפת?"
  - "בספריה הושאלו 20 ספרים, מתוכם 7 ספרי מדע. כמה ספרים אחרים הושאלו?"
  - "בקופסת הגירים היו 18 גירים. 4 נשברו. כמה גירים שלמים נשארו בקופסה?"
  - "רועי קנה 5 קרטוני חלב, בכל קרטון 2 ליטר חלב. כמה ליטר חלב קנה רועי?"
  - "במסיבה חילקו 30 בלונים ל-10 ילדים במספר שווה. כמה בלונים קיבל כל ילד?"
  - "בגן חיות ביקרו 25 ילדים. 11 מהם הלכו לראות את הפילים. כמה ילדים נשארו לראות חיות אחרות?"
  - "מורן כתבה 18 דפים ביומן. היא קראה שוב ורצתה למחוק 6 דפים. כמה דפים נשארו?"
  - "בכיתה 20 תלמידים. 8 לומדים חלילית והשאר לומדים ציור. כמה לומדים ציור?"
  - "ילדים אספו 15 צדפים בחוף. 5 נשברו בדרך. כמה צדפים שלמים נשארו?"
  - "אמא אפתה 24 עוגיות ושמה אותן על 4 צלחות שוות. כמה עוגיות בכל צלחת?"
  - "בעוגת יומולדת יש 12 נרות. אם דולקים רק 7 נרות, כמה נרות כבויים?"
  - "במגרש יש 18 כדורים, 6 נלקחו הביתה. כמה כדורים נשארו במגרש?"
  - "ליוסי היו 10 שקלים. הוא הוציא 3 שקלים על מסטיקים ועוד 4 שקלים על חטיף. כמה כסף נשאר ליוסי?"
  - "במסע אופניים רכבו 27 קילומטר בשתי תחנות שוות. כמה קילומטר בין תחנה לתחנה?"
  - "בימי החופש קראה רוני 14 ספרים. 5 ספרים היו על חיות. כמה ספרים לא היו על חיות?"
  - "אורי אסף 16 עלים בסתיו. הוא חילק אותם לאחיו ואחותו במספרים שווים. כמה עלים קיבל כל אחד?"
  - "6 תלמידים אספו 30 פקקים. כמה פקקים אסף כל תלמיד בממוצע?"
  - "בצנצנת יש 40 שקדים. אכלו 12 שקדים. כמה שקדים נשארו?"
  - "לאלי 28 מדבקות. היא נתנה 14 מדבקות לחברתה. כמה מדבקות נשארו לאלי?"
  - "טלי ציירה 9 ציורים ביום ראשון ו-6 ביום שני. כמה ציורים ציירה בשני הימים יחד?"
  - "במגרש היו 22 ילדים. 7 הלכו הביתה. כמה ילדים נשארו לשחק?"
  - "אייל קנה חבילת טושים עם 10 צבעים. הוא איבד 3 צבעים. כמה צבעים נשארו?"
  - "3 חברות קנו יחד 18 סופגניות. כמה סופגניות קיבלה כל אחת?"
  - "אמא קנתה 24 פרחים וחילקה אותם ל-6 אגרטלים שווים. כמה פרחים בכל אגרטל?"
  - "בבריכה שוחים 17 ילדים. 9 מהם יצאו להפסקה. כמה ילדים עדיין במים?"
  - "בגן יש 15 נדנדות. התקלקלו 4. כמה נדנדות תקינות נשארו?"
  - "דנה ארזה 20 מתנות ונתנה 5 מתנות לכל אחד מארבעת החברים. כמה מתנות חילקה?"
  - "בסלסילה היו 25 ענבים. איתי אכל 8. כמה ענבים נשארו?"
  - "נועה קנתה שתי חבילות עפרונות, בכל חבילה 5 עפרונות. כמה עפרונות יש לה?"
  - "בכיתה סידרו 18 כסאות ב-3 טורים שווים. כמה כסאות בכל טור?"
  - "ברק רץ 12 דקות בבוקר ו-9 דקות אחר הצהריים. כמה דקות רץ בסך הכול?"
  - "מספר הצעצועים של עדי גדול ב-7 ממספר הספרים שלה. אם יש לה 15 צעצועים, כמה ספרים יש לה?"
  - "לאורי 9 שקלים יותר מלאייל. אם לאייל 6 שקלים, כמה יש לאורי?"
  - "במאפייה מכרו 30 לחמניות. 12 היו לחמניות שומשום. כמה היו בלי שומשום?"
  - "4 תלמידים צבעו ביחד 20 ציורים במספר שווה. כמה ציורים צבע כל תלמיד?"
  - "אמא אפתה 18 פנקייקים. היא חילקה אותם בין שלושה ילדים שווה בשווה. כמה פנקייקים קיבל כל ילד?"
  - "בכיתה יש 10 שולחנות ו-30 כיסאות. כמה כיסאות בכל שולחן אם מחלקים שווה בשווה?"
  - "בכיתה היו 28 ספרי חשבון. הוסיפו עוד 17 ספרים. כמה ספרים יש כעת?"
  - "אמא אפתה 42 עוגיות וחילקה אותן שווה בשווה בין 6 ילדים. כמה עוגיות קיבל כל ילד?"
  - "במדף היו 55 צעצועים. 23 נמכרו. כמה צעצועים נשארו?"
  - "לרוני היו 64 אגורות. היא קנתה עיפרון ב־28 אגורות. כמה אגורות נשארו לה?"
  - "8 תלמידים אוספים בולים. כל תלמיד מצא 7 בולים. כמה בולים מצאו יחד?"
  - "בגן שתלו 36 שתילים בשורות של 4. כמה שורות יש?"
  - "בספריה השאילו 90 ספרים החודש. 45 היו ספרי הרפתקה. כמה ספרים לא היו הרפתקה?"
  - "במשק יש 72 תרנגולות. 24 נמכרו. כמה תרנגולות נשארו במשק?"
  - "אבא קנה 6 חבילות מים, בכל אחת 9 בקבוקים. כמה בקבוקים קנה בסך הכול?"
  - "לשלי 81 מדבקות. היא חילקה אותן בשווה בין 3 חברות. כמה קיבלה כל חברה?"
  - "בחג חילקו 100 שקיות ממתקים. אחרי שעה נותרו 37 שקיות. כמה שקיות חולקו כבר?"
  - "בסופר נמכרו 65 קילו תפוחים ו-27 קילו אגסים. כמה קילו פירות נמכרו בסך הכול?"
  - "אורי רץ 48 מטרים יותר מאיתי. אם איתי רץ 120 מטר, כמה רץ אורי?"
  - "תמר חסכה 95 שקלים. היא קנתה ספר ב־38 שקלים. כמה כסף נשאר לה?"
  - "5 שחקנים קלעו כל אחד 12 נקודות. כמה נקודות קלעה הקבוצה?"
  - "בכיתה יש 40 תלמידים. 8 תלמידים נעדרו. כמה תלמידים הגיעו?"
  - "בעוגת יום ההולדת 32 נרות. 14 כובו בנשיפה ראשונה. כמה נרות עדיין דולקים?"
  - "בכוס יש 250 מ\"ל מיץ. שתו 90 מ\"ל. כמה מיץ נשאר?"
  - "6 משאיות מובילות 8 קופסאות כל אחת. כמה קופסאות מועברות?"
  - "במרוץ אופניים רכבו 36 קילומטר בסך הכול. הרכיבה חולקה ל-4 מקטעים שווים. כמה קילומטר כל מקטע?"
  - "במבחן, אור קיבל 95 נקודות. הדר קיבלה 17 נקודות פחות. כמה קיבלה הדר?"
  - "במחסן יש 120 ארגזים. 3 פועלים מעבירים את הארגזים בשווה. כמה ארגזים לכל פועל?"
  - "מגדל המים מכיל 2,000 ליטר. השתמשו ב-650 ליטר להשקיה. כמה נשארו?"
  - "במפעל יוצרו 84 צעצועים בשעה. כמה צעצועים ייוצרו ב-7 שעות בקצב זה?"
  - "אמא חילקה 96 גולות בין 8 ילדים. כמה גולות קיבל כל ילד?"
  - "עמית קרא 132 עמודים בחודש. שליש מהם היו ספרי מדע. כמה עמודי מדע קרא?"
  - "בחצר 48 פרחים. שתלו עוד 32. כמה פרחים כעת?"
  - "משאית מובילה 54 שקי חול. הורידו 18 שקי חול באתר אחד. כמה שקי חול נשארו על המשאית?"
  - "עדן חסכה 78 שקלים. היא קיבלה עוד 25 שקלים מדודה. כמה יש לה עכשיו?"
  - "בבית הספר יש 9 כיתות, בכל כיתה 26 תלמידים. כמה תלמידים בבית הספר?"
  - "בספר יש 144 עמודים. דניאל קרא רבע מהם. כמה עמודים קרא?"
  - "לטיול חילקו 72 בקבוקי מים ל-12 קבוצות. כמה בקבוקים לכל קבוצה?"
  - "במקרר 60 ביצים. בישלו 2 תריסר ביצים. כמה ביצים נשארו?"
  - "בריצה, מאיה חצתה קו הסיום בזמן של 75 שניות, שהוא 9 שניות מהר יותר מירון. כמה שניות לקח לירון?"
  - "בחנות הבגדים היו 88 חולצות. מכרו 3 תריסרים מהן. כמה חולצות נשארו?"
  - "ישראל שתל 56 עצים לאורך שביל בשתי שורות שוות. כמה עצים בכל שורה?"
  - "שחר אכל 3⁄8 מכמות של 64 גרם שוקולד. כמה גרם אכל?"
  - "לירון יש 90 קלפים. הוא חילק אותם באופן שווה בין 5 חברים. כמה קלפים לכל אחד?"
  - "במגדל 150 מדרגות. רות טיפסה 62 מדרגות. כמה מדרגות נשארו לטפס?"
  - "בתחנת הדלק מכרו 72 ליטר דלק בשעה. כמה ימכרו ב-3 שעות?"
  - "ילדי הכיתה אספו 96 שקלים לצדקה. הסכום חולק בשווה בין 4 עמותות. כמה קיבלה כל עמותה?"
  - "על דוכן פירות מונחים 88 תפוזים. אם מוכרים 2 תריסרים, כמה תפוזים נשארו?"
  - "ירקות במשקל 63 ק\"ג חולקו ל-9 שקיות שוות. כמה ק\"ג בכל שקית?"
  - "10 תלמידים כתבו כל אחד 18 ברכות. כמה ברכות נכתבו?"
  - "קופסה מכילה 108 חלקי לגו. אם 36 חלקים הוצאו, כמה חלקים נשארו?"
  - "בבנק חסכו 240 שקלים בשלושה תאי חיסכון בשווה. כמה בכל תא?"
  - "מטוס טס 540 ק\"מ בשלוש שעות בקצב אחיד. כמה ק\"מ בכל שעה?"
  - "מחירו של ספר עלה מ-48 שקלים ל-68 שקלים. בכמה עלה?"
  - "למירי היו 72 גולות. היא נתנה חמישית מהן לאחותה. כמה נתנה?"
  - "במבצע נמכרו 45 בקבוקים מתוך 120 במלאי. כמה בקבוקים נשארו?"

Number_Series_Simple_Patterns:
  - "2, 4, 6, 8, ___"
  - "5, 7, 9, 11, ___"
  - "1, 3, 6, 10, ___"
  - "9, 7, 5, 3, ___"
  - "3, 6, 9, 12, ___"
  - "10, 9, 8, 7, ___"
  - "4, 8, 12, 16, ___"
  - "7, 10, 13, 16, ___"
  - "15, 12, 9, 6, ___"
  - "2, 5, 8, 11, ___"
  - "1, 2, 4, 8, ___"
  - "12, 10, 8, 6, ___"
  - "6, 9, 12, 15, ___"
  - "20, 18, 16, 14, ___"
  - "3, 5, 7, 9, ___"
  - "11, 9, 7, 5, ___"
  - "2, 3, 5, 8, ___"
  - "14, 12, 10, 8, ___"
  - "5, 10, 15, 20, ___"
  - "18, 15, 12, 9, ___"
  - "1, 4, 7, 10, ___"
  - "9, 6, 3, 0, ___"
  - "2, 4, 8, 16, ___"
  - "13, 11, 9, 7, ___"
  - "4, 5, 7, 10, ___"
  - "16, 14, 12, 10, ___"
  - "3, 6, 12, 24, ___"
  - "8, 7, 6, 5, ___"
  - "2, 6, 10, 14, ___"
  - "7, 5, 3, 1, ___"
  - "5, 9, 13, 17, ___"
  - "12, 9, 6, 3, ___"
  - "6, 8, 10, 12, ___"
  - "10, 8, 6, 4, ___"
  - "1, 3, 5, 7, ___"
  - "9, 12, 15, 18, ___"
  - "14, 11, 8, 5, ___"
  - "2, 5, 9, 14, ___"
  - "18, 16, 14, 12, ___"
  - "4, 7, 10, 13, ___"
  - "3, 9, 27, 81, ___"
  - "20, 17, 14, 11, ___"
  - "1, 5, 9, 13, ___"
  - "6, 5, 4, 3, ___"
  - "7, 14, 21, 28, ___"
  - "15, 12, 9, 6, ___"
  - "2, 8, 14, 20, ___"
  - "11, 8, 5, 2, ___"
  - "5, 6, 8, 11, ___"
  - "16, 12, 8, 4, ___"
  - "3, 7, 11, 15, ___"
  - "2, 5, 9, 14, 20, ___"
  - "3, 6, 12, 24, ___"
  - "10, 15, 21, 28, ___"
  - "4, 8, 16, 32, ___"
  - "7, 11, 18, 29, ___"
  - "25, 20, 16, 13, ___"
  - "1, 4, 9, 16, ___"
  - "5, 9, 14, 20, ___"
  - "12, 22, 32, 42, ___"
  - "30, 27, 24, 21, ___"
  - "6, 8, 12, 20, ___"
  - "11, 22, 44, 88, ___"
  - "9, 18, 27, 36, ___"
  - "2, 6, 18, 54, ___"
  - "13, 11, 9, 7, ___"
  - "15, 17, 20, 24, ___"
  - "8, 14, 21, 29, ___"
  - "40, 35, 31, 28, ___"
  - "4, 7, 11, 16, ___"
  - "16, 8, 4, 2, ___"
  - "3, 9, 27, 81, ___"
  - "21, 18, 15, 12, ___"
  - "1, 2, 4, 7, 11, ___"
  - "50, 45, 40, 35, ___"
  - "6, 10, 15, 21, ___"
  - "2, 3, 5, 8, 13, ___"
  - "9, 12, 16, 21, ___"
  - "20, 18, 15, 11, ___"
  - "1, 3, 6, 10, 15, ___"
  - "5, 25, 125, ___"
  - "2, 4, 7, 11, ___"
  - "45, 36, 28, 21, ___"
  - "6, 12, 36, 144, ___"
  - "32, 31, 29, 26, ___"
  - "4, 9, 16, 25, ___"
  - "3, 5, 9, 17, ___"
  - "2, 5, 11, 23, ___"
  - "64, 32, 16, 8, ___"
  - "10, 20, 25, 50, 55, ___"
  - "7, 9, 12, 16, 21, ___"
  - "1, 4, 10, 20, ___"
  - "50, 48, 44, 38, 30, ___"
  - "16, 18, 21, 25, ___"
  - "81, 72, 63, 54, ___"
  - "3, 8, 15, 24, ___"
  - "100, 90, 81, 73, ___"
  - "2, 8, 18, 32, ___"
  - "6, 9, 13, 18, 24, ___"
  - "22, 17, 13, 10, ___"
  - "4, 12, 36, 108, ___"

Picture_Based_Image_Arithmetic_Puzzles:
  - "אם 🍎 + 🍎 = 6 ו-🍎 + 🍐 = 9, כמה שווה 🍐?"
  - "אם 🌟 + 🌟 + 🌟 = 15 ו-🌟 + ☀️ = 11, כמה שווה ☀️?"
  - "אם 🐠 + 🐟 = 10 ו-🐟 = 4, כמה שווה 🐠?"
  - "אם ⚽ + ⚽ = 8 ו-⚽ + 🏀 = 11, מה הערך של 🏀?"
  - "אם 💎 × 2 = 14 ו-💎 + 🔶 = 10, כמה שווה 🔶?"
  - "אם 🖍️ + 🖍️ + 🖍️ = 12 ו-🖍️ + ✏️ = 7, מה הערך של ✏️?"
  - "אם 🍰 − 🍪 = 4 ו-🍪 = 3, כמה שווה 🍰?"
  - "אם 🐱 + 🐶 = 13 ו-🐶 = 6, מה הערך של 🐱?"
  - "אם 🚗 + 🚗 = 18 ו-🚗 + 🚲 = 25, כמה שווה 🚲?"
  - "אם 🌼 + 🌼 = 10 ו-🌼 + 🌻 = 15, כמה שווה 🌻?"
  - "אם 🎈 + 🎈 + 🎈 = 9 ו-🎈 + 🎁 = 7, מה הערך של 🎁?"
  - "אם 🍄 + 🍄 = 8 ו-🍄 + 🌲 = 11, כמה שווה 🌲?"
  - "אם 🦋 × 2 = 18 ו-🦋 + 🐞 = 13, מה ערך 🐞?"
  - "אם ⚡ + ⚡ = 14 ו-⚡ + 🔋 = 20, כמה שווה 🔋?"
  - "אם 🍒 + 🍒 + 🍒 = 21 ו-🍒 + 🍇 = 12, כמה שווה 🍇?"
  - "אם 🏰 − 🗼 = 5 ו-🗼 = 7, מה הערך של 🏰?"
  - "אם 🌕 + 🌕 = 12 ו-🌕 + 🌖 = 17, כמה שווה 🌖?"
  - "אם 🚀 + 🚀 = 16 ו-🚀 + ✈️ = 22, מה ערך ✈️?"
  - "אם 🐻 + 🐻 = 20 ו-🐻 + 🐼 = 27, כמה שווה 🐼?"
  - "אם 🎸 + 🎸 + 🎸 = 24 ו-🎸 + 🥁 = 18, מה ערך 🥁?"
  - "אם 🍓 + 🍓 = 10 ו-🍓 + 🍑 = 14, כמה שווה 🍑?"
  - "אם 📚 + 📚 = 12 ו-📚 + 🖋️ = 15, מה ערך 🖋️?"
  - "אם 🧩 + 🧩 + 🧩 = 18 ו-🧩 + 🎲 = 13, כמה שווה 🎲?"
  - "אם 🌈 − ☁️ = 3 ו-☁️ = 6, מה ערך 🌈?"
  - "אם 🐢 + 🐢 = 8 ו-🐢 + 🐇 = 15, כמה שווה 🐇?"
  - "אם 🛸 × 2 = 22 ו-🛸 + 🚁 = 15, מה ערך 🚁?"
  - "אם 🍔 + 🍔 = 12 ו-🍔 + 🍟 = 17, כמה שווה 🍟?"
  - "אם 🎯 + 🎯 + 🎯 = 27 ו-🎯 + 🏆 = 19, מה ערך 🏆?"
  - "אם 🌳 + 🌳 = 14 ו-🌳 + 🌴 = 23, כמה שווה 🌴?"
  - "אם 🖥️ − 📱 = 7 ו-📱 = 6, מה ערך 🖥️?"
  - "אם 🌺 + 🌺 = 18 ו-🌺 + 🌹 = 24, כמה שווה 🌹?"
  - "אם 🕯️ + 🕯️ + 🕯️ = 15 ו-🕯️ + 🔦 = 11, מה ערך 🔦?"
  - "אם 🐝 + 🐝 = 10 ו-🐝 + 🦋 = 15, כמה שווה 🦋?"
  - "אם 🔑 × 2 = 16 ו-🔑 + 🔒 = 13, מה ערך 🔒?"
  - "אם 🏀 + 🏀 = 20 ו-🏀 + 🏈 = 27, כמה שווה 🏈?"
  - "אם 🍩 + 🍩 + 🍩 = 24 ו-🍩 + 🍪 = 17, מה ערך 🍪?"
  - "אם ⛵ − 🚣 = 4 ו-🚣 = 5, מה ערך ⛵?"
  - "אם 🎻 + 🎻 = 16 ו-🎻 + 🎺 = 21, מה ערך 🎺?"
  - "אם 🌟 + 🌟 + 🌟 = 21 ו-🌟 + 🌜 = 17, כמה שווה 🌜?"
  - "אם 🖌️ + 🖌️ = 12 ו-🖌️ + 🖍️ = 15, מה ערך 🖍️?"
  - "אם 🧸 + 🧸 = 18 ו-🧸 + 🪀 = 25, כמה שווה 🪀?"
  - "אם 📀 × 2 = 10 ו-📀 + 📼 = 9, מה ערך 📼?"
  - "אם 🍎 + 🍐 + 🍎 = 14 ו-🍐 = 4, כמה שווה 🍎?"
  - "אם 🎲 + 🎲 = 14 ו-🎲 + ♟️ = 19, כמה שווה ♟️?"
  - "אם 🐳 + 🐳 = 26 ו-🐳 + 🐬 = 33, מה ערך 🐬?"
  - "אם 🍯 − 🍋 = 2 ו-🍋 = 3, מה ערך 🍯?"
  - "אם 🚲 + 🚲 + 🚲 = 18 ו-🚲 + 🛴 = 13, מה ערך 🛴?"
  - "אם 🧁 + 🧁 = 10 ו-🧁 + 🍦 = 15, כמה שווה 🍦?"
  - "אם 🕹️ + 🕹️ = 20 ו-🕹️ + 🎮 = 28, מה ערך 🎮?"
  - "אם 🥅 + 🥅 + 🥅 = 21 ו-🥅 + 🏒 = 16, מה ערך 🏒?"
  - "אם 🕰️ − ⏰ = 4 ו-⏰ = 7, מה ערך 🕰️?"
  - "אם 📷 + 📷 = 24 ו-📷 + 🎥 = 31, מה ערך 🎥?"
  - "אם 🍏 + 🍏 + 🍏 = 24 ו-🍏 + 🍑 = 18, כמה שווה 🍑?"
  - "אם 🚗 × 3 = 45 ו-🚗 + 🚲 = 20, מה ערך 🚲?"
  - "אם 🌟 + 🌟 = 22 ו-🌟 − 🌙 = 6, כמה שווה 🌙?"
  - "אם 🐶 + 🐶 + 🐱 = 34 ו-🐱 = 12, מה ערך 🐶?"
  - "אם ⚽ + 🏀 = 25 ו-🏀 = 14, כמה שווה ⚽?"
  - "אם 💎 × 2 = 38 ו-💎 + 🔶 = 27, כמה שווה 🔶?"
  - "אם 🌼 + 🌼 + 🌻 = 29 ו-🌻 = 11, מה ערך 🌼?"
  - "אם 🎈 × 4 = 48 ו-🎈 + 🎁 = 17, מה ערך 🎁?"
  - "אם 🦋 + 🦋 = 30 ו-🦋 + 🐞 = 37, כמה שווה 🐞?"
  - "אם 🏰 − 🗼 = 9 ו-🗼 = 15, מה ערך 🏰?"
  - "אם 🍒 + 🍒 = 26 ו-🍒 + 🍇 = 35, כמה שווה 🍇?"
  - "אם 📚 × 3 = 60 ו-📚 + 🖋️ = 25, כמה שווה 🖋️?"
  - "אם 🧩 + 🧩 + 🧩 = 54 ו-🧩 + 🎲 = 22, מה ערך 🎲?"
  - "אם 🌈 − ☁️ = 8 ו-☁️ = 14, מה ערך 🌈?"
  - "אם 🐢 + 🐢 + 🐇 = 43 ו-🐇 = 19, כמה שווה 🐢?"
  - "אם 🍔 + 🍔 = 34 ו-🍔 + 🍟 = 47, כמה שווה 🍟?"
  - "אם 🎯 × 2 = 50 ו-🎯 + 🏆 = 33, מה ערך 🏆?"
  - "אם 🌳 + 🌳 = 40 ו-🌳 + 🌴 = 58, כמה שווה 🌴?"
  - "אם 🎻 + 🎻 + 🎺 = 70 ו-🎺 = 28, מה ערך 🎻?"
  - "אם 🦉 + 🦉 = 38 ו-🦉 + 🐦 = 52, כמה שווה 🐦?"
  - "אם 🖥️ − 📱 = 12 ו-📱 = 18, מה ערך 🖥️?"
  - "אם 🌺 + 🌺 + 🌹 = 57 ו-🌹 = 21, כמה שווה 🌺?"
  - "אם 🕯️ × 4 = 44 ו-🕯️ + 🔦 = 17, מה ערך 🔦?"
  - "אם 🐝 + 🐝 = 26 ו-🐝 + 🦋 = 38, כמה שווה 🦋?"
  - "אם 🔑 × 3 = 63 ו-🔑 + 🔒 = 27, מה ערך 🔒?"
  - "אם 🏀 + 🏀 + 🏈 = 86 ו-🏈 = 32, כמה שווה 🏀?"
  - "אם 🍩 + 🍩 = 48 ו-🍩 + 🍪 = 63, כמה שווה 🍪?"
  - "אם ⛵ + ⛵ = 44 ו-⛵ + 🚣 = 59, מה ערך 🚣?"
  - "אם 🎲 × 2 = 56 ו-🎲 + ♟️ = 41, מה ערך ♟️?"
  - "אם 🐳 + 🐳 + 🐬 = 90 ו-🐬 = 36, כמה שווה 🐳?"
  - "אם 🍯 − 🍋 = 7 ו-🍋 = 11, מה ערך 🍯?"
  - "אם 🚲 × 3 = 75 ו-🚲 + 🛴 = 32, מה ערך 🛴?"
  - "אם 🧁 + 🧁 + 🍦 = 68 ו-🍦 = 26, כמה שווה 🧁?"
  - "אם 🕹️ × 2 = 46 ו-🕹️ + 🎮 = 31, מה ערך 🎮?"
  - "אם 🥅 + 🥅 = 48 ו-🥅 + 🏒 = 70, מה ערך 🏒?"
  - "אם 🕰️ − ⏰ = 9 ו-⏰ = 23, מה ערך 🕰️?"
  - "אם 📷 + 📷 + 🎥 = 110 ו-🎥 = 50, כמה שווה 📷?"
  - "אם 🍎 + 🍐 + 🍇 = 64 ו-🍇 = 19 ו-🍐 = 15, מה ערך 🍎?"
  - "אם 🎸 × 2 = 58 ו-🎸 + 🥁 = 45, מה ערך 🥁?"
  - "אם ⚡ + ⚡ + 🔋 = 82 ו-🔋 = 28, כמה שווה ⚡?"
  - "אם 🌟 × 3 = 75 ו-🌟 + 🌜 = 32, כמה שווה 🌜?"
  - "אם 💡 + 💡 = 40 ו-💡 + 🔌 = 53, מה ערך 🔌?"
  - "אם 🐠 + 🐠 + 🐟 = 73 ו-🐟 = 29, כמה שווה 🐠?"
  - "אם 🏡 − 🏠 = 11 ו-🏠 = 34, מה ערך 🏡?"
  - "אם 🎀 + 🎀 + 🎁 = 61 ו-🎁 = 25, כמה שווה 🎀?"
  - "אם 🛹 × 2 = 38 ו-🛹 + 🚂 = 29, מה ערך 🚂?"
  - "אם 🐾 + 🐾 = 46 ו-🐾 + 🐺 = 65, כמה שווה 🐺?"
  - "אם 🍓 + 🍓 + 🍑 = 77 ו-🍑 = 31, כמה שווה 🍓?"
  - "אם 📀 × 3 = 69 ו-📀 + 📼 = 28, מה ערך 📼?"
  - "אם 🐧 + 🐧 + 🐦 = 88 ו-🐦 = 34, כמה שווה 🐧?"
