Multi_Step_Arithmetic_Word_Problems:
  - "לדניאל היו 30 ₪ מסבא ו-18 ₪ מסבתא. הוא קנה צעצוע ב-32 ₪ ועוד ממתק ב-4 ₪. כמה כסף נשאר לו?"
  - "אבא אפה 48 עוגיות. הוא חילק 15 עוגיות לעבודה והגיש 12 עוגיות בבית. כמה עוגיות נשארו במטבח?"
  - "בכיתה ארגנו יריד. תלמידים מכרו 3 חבילות מדבקות, בכל חבילה 8 מדבקות, ועוד 2 חבילות של 10 מדבקות. כמה מדבקות נמכרו בסך הכול?"
  - "לירון 24 גולות. הוא קנה עוד 17 גולות, ואחר-כך חילק 15 גולות לשני חברים בשווה. כמה גולות נשארו לו?"
  - "בחוג אמנות הכינו 6 קופסאות צבע, בכל קופסה 5 עפרונות. אחר-כך הוסיפו עוד 8 עפרונות בודדים לקופסאות. כמה עפרונות יש כעת?"
  - "בגן שתלו 36 עציצים בשלוש שורות שוות. חצי מהעציצים קושטו בסרטים. כמה עציצים נשארו בלי סרט?"
  - "לטיול אספו 120 ₪. הוצאות האוטובוס היו 78 ₪, והגשם החזיר 10 ₪ לחסכון. כמה כסף נשאר לאחר ההחזר?"
  - "בשוק קנו 4 סלים עם 6 תפוחים בכל סל ועוד 9 תפוחים מפוזרים. אם אכלו 7 תפוחים, כמה נשארו?"
  - "במדף היו 60 ספרים. 22 הושאלו, ואחר-כך הוחזרו 13. כמה ספרים יש כעת על המדף?"
  - "למיכל היו 45 תגיות. היא חילקה 18 תגיות לאירוע ו-9 תגיות נשארו ללא שימוש. כמה תגיות חילקה לכל היתר?"
  - "אביב רץ 400 מ׳ בשני מקטעים שווים, ואז הוסיף עוד 150 מ׳. מה מרחק הריצה הכולל?"
  - "במסיבה חילקו 90 בלונים ל-6 שולחנות בשווה. 2 בלונים מכל שולחן התפוצצו. כמה בלונים נשארו?"
  - "הגננת הכינה 4 מגשים עם 8 עוגיות כל אחד ועוד מגש נוסף עם 6 עוגיות. הילדים אכלו 25 עוגיות. כמה עוגיות נשארו?"
  - "בעקבות תרומה נוספו 27 ספרים לספרייה שהיו בה כבר 58 ספרים. אם אחר-כך הושאלו 31 ספרים, כמה ספרים נשארו?"
  - "סבתא חילקה 35 שוקולדים בין 5 נכדים בשווה. אחד הנכדים נתן 2 שוקולדים לחבר. כמה שוקולדים נשארו לכל נכד אחר?"
  - "בכיתה הדפיסו 4 חוברות, בכל חוברת 12 עמודים. לאחר מכן הוסיפו לחוברת אחת עוד 6 עמודים. כמה עמודים בסך הכול כעת?"
  - "בטיול אספו 28 אבנים צבעוניות. בדרך חזרה אבדה חמישית מהן ונמצאו עוד 3 אבנים חדשות. כמה אבנים יש כעת?"
  - "אמא קנתה 3 חבילות מיץ, בכל חבילה 4 בקבוקים. חילקו בקבוק אחד לכל אחד מ-8 ילדים. כמה בקבוקים נשארו?"
  - "בסל קיים היו 42 תפוזים. שליש מהם נסחטו למיץ. אחר-כך נוספו 10 תפוזים חדשים. כמה יש כעת?"
  - "בכיתה יש 24 ילדים. כל ילד תרם 5 ₪ לטיול, והמורה הוסיפה עוד 30 ₪. כמה כסף נאסף?"
  - "נעמה קנתה 5 דפים ב-3 ₪ כל אחד ועוד מחברת ב-8 ₪. היה לה 30 ₪. כמה עודף קיבלה?"
  - "במרוץ מורים-תלמידים רץ צוות התלמידים 280 מ׳ בכל סבב במשך 3 סבבים. כמה מטרים רצו בסך הכול?"
  - "12 תלמידים בנו מגדלי לגו. לכל תלמיד היו 15 קוביות, אך 36 קוביות נשברו. כמה קוביות שלמות נשארו?"
  - "אמא חילקה 54 מדבקות בין 9 ילדים. לאחר מכן קנתה עוד 18 מדבקות וחילקה אותן שוב בשווה. כמה מדבקות נוספו לכל ילד?"
  - "בכיתה הכינו 40 ציורים. רבע מהם נשלחו לתערוכה, ועוד 6 נמסרו להורים. כמה ציורים נשארו בכיתה?"
  - "במשחק אספו 3 קבוצות 18 נקודות כל אחת ועוד קבוצת בונוס אספה 12 נקודות. כמה נקודות בסך הכול?"
  - "רכבת נסעה 90 ק״מ בשעה. אחרי שעה עצרה 15 דקות ואז נסעה עוד 60 ק״מ. כמה ק״מ נסעה הרכבת?"
  - "בשדה גדלים 5 ערוגות, בכל ערוגה 9 שיחים. 7 שיחים בכל הערוגות יחד נבלו. כמה שיחים בריאים נשארו?"
  - "קופת חסכון כללה 200 ₪. ילד משך 30 ₪ לקנות משחק והחזיר אחר-כך 15 ₪. כמה כסף כעת בקופה?"
  - "בבריכת הכדורים היו 120 כדורים. 3 ילדים הוציאו כל אחד 18 כדורים למשחק. כמה כדורים נשארו בבריכה?"
  - "הודיה שקלה 42 מדבקות. היא הוסיפה למעטפה עוד 3 מדבקות בכל אחת מ-4 חבילות. כמה מדבקות בסך הכול?"
  - "לאירוע הזמינו 84 כוסות. חולקו 60 כוסות ו-8 כוסות נשברו. כמה כוסות חד-פעמיות נשארו לשימוש?"
  - "במאפייה נאפו 5 מגשים עם 10 לחמניות כל אחד ועוד מגש אחד עם 8 לחמניות. 27 לחמניות נמכרו. כמה נשארו?"
  - "תאומים אספו יחד 48 גלויות. הם חילקו ביניהם שווה בשווה ואז נתנו 3 גלויות לחברה. כמה גלויות נשארו לכל אח?"
  - "בטיול חולקו 96 עוגיות ל-12 ילדים. אחר-כך נוספו עוד 24 עוגיות וחולקו שוב שווה בשווה. כמה עוגיות נוספו לכל ילד?"
  - "במחסן היו 140 בקבוקים. נמכרו 3 ארגזים של 12 בקבוקים ועוד 20 בקבוקים בודדים. כמה בקבוקים נשארו?"
  - "הדפיסו 4 ערימות של 25 עלונים ועוד ערימה אחת עם 17 עלונים. חילקו 63 עלונים. כמה עלונים נותרו?"
  - "בחוג שחייה השתתפו 30 ילדים. 20 ילדים קנו כובעים ב-10 ₪ כל אחד. כמה כסף שולם על הכובעים?"
  - "לשולחן פאי אפו 6 עוגות פאי. בכל עוגה חתכו 8 פרוסות. נמכרו 35 פרוסות. כמה פרוסות נשארו?"
  - "גינת ירק מחולקת ל-5 מיטות. בכל מיטה 7 שתילים. 8 שתילים נשרו. כמה שתילים בריאים נשארו?"
  - "ילדים מילאו 3 דליים ב-12 בלונים כל אחד ועוד דלי נוסף ב-8 בלונים. אם 15 בלונים התפוצצו, כמה נשארו?"
  - "במרכז ספורט 4 קבוצות משחקות. כל קבוצה כבשה 6 שערים. אחר-כך קבוצה אחת כבשה עוד 4 שערים. כמה שערים בסך הכול?"
  - "בכיתה כתבו 64 ברכות חג. מחצית הודפסו בצבע. כמה ברכות נשארו בשחור-לבן?"
  - "לנוי היו 72 צורות נייר. היא חילקה אותן ל-6 חברים בשווה והדביקה 6 צורות על כרטיס ברכה. כמה נשארו?"
  - "בחדרה 48 ספרים. היא הוסיפה עוד 2 מדפים עם 6 ספרים בכל מדף. כמה ספרים יש כעת?"
  - "למורה היו 120 נקודות פרסים. היא חילקה 3 נקודות לכל אחד מ-25 תלמידים. כמה נקודות נשארו?"
  - "במפעל יצרו 5 קופסאות של 18 בובות ועוד קופסה אחת של 12 בובות. נשלחו 60 בובות לחנות. כמה נשארו במחסן?"
  - "אייל קרא 24 עמודים ביום שני ועוד פי שניים מזה ביום שלישי. כמה עמודים קרא בשני הימים יחד?"
  - "בטבלה 6 עמודות של 5 מספרים. אם מחקו 9 מספרים בסך הכול, כמה מספרים נשארו בטבלה?"
  - "בקרטון 100 ביצים. 4 תריסרים נמכרו ו-10 ביצים נשברו. כמה ביצים שלמות נשארו?"

Number_Series_Advanced_Patterns:
  - "2, 6, 12, 20, 30, ___"
  - "3, 9, 18, 30, 45, ___"
  - "5, 8, 12, 17, 23, ___"
  - "1, 4, 8, 13, 19, ___"
  - "7, 11, 16, 22, 29, ___"
  - "9, 18, 27, 36, 45, ___"
  - "2, 4, 8, 16, 32, ___"
  - "10, 15, 21, 28, 36, ___"
  - "12, 10, 18, 16, 24, ___"
  - "4, 7, 11, 16, 22, ___"
  - "6, 12, 24, 48, 96, ___"
  - "11, 14, 18, 23, 29, ___"
  - "8, 13, 19, 26, 34, ___"
  - "3, 5, 9, 17, 33, ___"
  - "2, 5, 9, 14, 20, ___"
  - "15, 12, 24, 21, 42, ___"
  - "5, 10, 18, 29, 43, ___"
  - "20, 18, 16, 14, 12, ___"
  - "1, 2, 4, 7, 11, ___"
  - "30, 25, 20, 15, 10, ___"
  - "3, 8, 13, 18, 23, ___"
  - "12, 14, 18, 24, 32, ___"
  - "6, 9, 13, 18, 24, ___"
  - "25, 20, 15, 10, 5, ___"
  - "2, 6, 12, 20, 30, ___"
  - "9, 17, 25, 33, 41, ___"
  - "4, 12, 20, 28, 36, ___"
  - "5, 16, 27, 38, 49, ___"
  - "7, 9, 12, 16, 21, ___"
  - "8, 24, 48, 80, 120, ___"
  - "13, 18, 24, 31, 39, ___"
  - "2, 3, 5, 8, 12, ___"
  - "6, 11, 17, 24, 32, ___"
  - "14, 12, 24, 22, 44, ___"
  - "1, 5, 9, 13, 17, ___"
  - "11, 22, 33, 44, 55, ___"
  - "4, 9, 15, 22, 30, ___"
  - "16, 12, 24, 20, 40, ___"
  - "3, 7, 12, 18, 25, ___"
  - "10, 21, 33, 46, 60, ___"
  - "6, 14, 22, 30, 38, ___"
  - "9, 27, 81, 243, ___"
  - "5, 7, 10, 14, 19, ___"
  - "8, 12, 17, 23, 30, ___"
  - "18, 15, 12, 9, 6, ___"
  - "2, 8, 18, 32, 50, ___"
  - "11, 19, 27, 35, 43, ___"
  - "4, 6, 10, 18, 34, ___"
  - "12, 21, 30, 39, 48, ___"
  - "7, 13, 21, 31, 43, ___"
  - "3, 11, 19, 27, 35, ___"

Numbers_in_Shapes_Puzzles:
  - "בלוח 2×2: בשורה הראשונה 7 ו-5, ובשורה השנייה 4 ו-?. בכל שורה ועמודה הסכום 12. מה המספר החסר?"
  - "במשולש מספרים: שני הקודקודים התחתונים הם 6 ו-9. הקודקוד העליון הוא סכומם. מה צריך להיות ב-?‎"
  - "במלבן 2×3: 8, ? ,4 בשורה העליונה; 5, 7, ? בשורה התחתונה. כל עמודה סכום 13. מה חסר?"
  - "בצלב מספרים: במרכז 5. הארבע קצוות צריכים שסכום כל זוג מנוגד יהיה 12. אם למעלה 8 ולמטה ?, כמה צריך בימין ובשמאל לסגור את התבנית?"
  - "שלושה מעגלים מחוברים בשרשרת: הסכום בשני קצוות הוא 18, וכל מעגל אמצעי הוא הפרש בין שני השכנים. אם בקצה אחד 11 ובאמצעי ?, מה בקצה השני?"
  - "במשולש: על כל צלע סכום שני המספרים הוא 14. בקודקוד אחד 3, בשני ?, ובשלישי 7. מה המספר החסר?"
  - "בלוח 3×3: האמצע 10. כל שורה, עמודה ואלכסון סכומם 24. בשורה העליונה 9, ? ,7. מה המספר החסר?"
  - "בכוכב דוד עם שישה קודקודים: כל זוג קודקודים שממול סכומם 15. אם יש 4 מול ?, מה צריך להיות ב-?"
  - "בעץ מספרים: שורש = סכום שני בניו; כל בן = סכום ילדיו. אם ברמת העלים 4 ו-6, מה צריך להיות בשורש?"
  - "בבית מספרים: הגג הוא סכום הקירות. קירות: 8 ו-?. אם הדלת (סכום הקירות) היא 20, מה המספר החסר?"
  - "בלוח 2×2: 9 ו-? בשורה ראשונה, 3 ו-? בשורה שנייה. כל עמודה אותו מכפלה 27. מהם המספרים החסרים?"
  - "במשולש מתמלא: שני התחתונים 5, ?‎. המספר שבאמצע הצלע התחתונה הוא הסכום שלהם, והעליון הוא הסכום של שני המספרים שבאמצע. אם באמצע העליון צריך להגיע ל-20, מה ?"
  - "בטבלה 3×1 (עמודה): 4, ? ,16. כל מספר אמצעי הוא הממוצע של זה שמעליו ומתחתיו. מה המספר החסר?"
  - "במשולש: 2 בפינה שמאלית, ? בפינה ימנית, והבסיס שווה 15. סכום התחתונים 15 ושווה ל-? + 2. מה ?"
  - "בלוח 3×3: פינות 4, ? ,? ,10. כל שורה סכומה 21. מה הערכים החסרים?"
  - "בכנפיים של פרפר: גוף 6. כל כנף עליונה + תחתונה סכומן שווה 14. אם כנף עליונה ימין 9, מה כנף תחתונה ימין?"
  - "בשרשרת מספרים עגולה של 4: כל מספר הוא סכום השניים הקודמים פחות 2. מתחילים 3, 5, ?. מה המספר הרביעי?"
  - "בטרפז: בסיס עליון 7 ו-?. בסיס תחתון סכום שניהם. אם הבסיס התחתון 22, מה ?"
  - "בשביל מספרים מעגלי: כל שלישייה רצופה סכומה 18. רצף 6, ?‎,?, 8. מה שני המספרים החסרים?"
  - "בלוח 2×3: 6, ?, 9 בשורה ראשונה; 5, ?, 4 בשורה שנייה. כל עמודה סכום 11. מצא ?"
  - "בפירמידה: שורה תחתונה 3, 7, ?. כל אבן היא סכום שתי האבנים שמתחתיה. שורת הביניים ?, ?. הפסגה ?. מה המספרים החסרים כדי שהפסגה תהיה 20?"
  - "במשולש שווה-צלעות עם נקודה באמצע: סכום שני מספרים בבסיס שווה למספר בנקודת האמצע. אם הבסיס 6 ו-?, והאמצע 13, מה ?"
  - "בלוח 3×3: המרכז 9. כל עמודה סכום 24. העמודה הראשונה 7, ?‎,?. מצא שני המספרים החסרים."
  - "בשביל מספרים ליניארי: כל מספר שלישי הוא סכום השניים הקודמים. 2, 3, ?, ?, ?. מה המספרים החסרים?"
  - "בבית ספרותי: חלון הוא מכפלת שני קירות. קירות: 4 ו-?. אם חלון 28, מה ?"
  - "בשרשרת 5 עיגולים: סכום ראשון ושלישי שווה רביעי; סכום שני וחמישי שווה רביעי. נתון 6, ?, ?, ?, 5. מה ?"
  - "בלוח 2×2: המכפלה בשורה העליונה 40, בשורה התחתונה 30. בשורה העליונה 8 ו-?, בשורה תחתונה 5 ו-?. מצא ?"
  - "בכוכב בעל חמש קודקודים: סכום כל שתי נקודות סמוכות 18. אם סדר המספרים 7, ?, ?, ?, ?. מה השאר?"
  - "במעגל 6 מספרים: כל שני מספרים סמוכים שונים ב-3. אם מתחילים 4 ואז ?, מה רצף המספרים?"
  - "במשולש מספרים: 4, ? בבסיס, והפסגה היא מכפלתם חלקי 2. אם בפסגה צריך להיות 14, מה ?"
  - "בטבלת 2×2: סכומי האלכסונים שווים. פינות שמאל עליון 6, ימין תחתון 10, האחרים ? ו-?. מצא הערכים כדי שהסכום יהיה 16."
  - "בלוח 3×3: כל שורה סדרה חשבונית באותו הפרש. שורה ראשונה 3, ?, ?. שורה שנייה 6, ?, ?. שורה שלישית 9, ?, ?. מצא ? כך שההפרש אחיד."
  - "בשרשרת משולשים: פסגה ראשונה 5, כל פסגה נוספת היא סכום שני המספרים בפסגה הקודמת. מה הפסגה השלישית?"
  - "במתומן: סכום כל שני מספרים בדילוג אחד שווה 20. אם אחת הצלעות 8, מה שתי הצלעות הסמוכות?"
  - "בלוח 2×3: 4 ו-? בשורה עליונה; 8 ו-? בשורה תחתונה. סכום כל עמודה 15. מצא ?"
  - "בפירמידה דו-שכבתית: בסיס 5, ?, 9. קומה שנייה ?, ?. פסגה ?. פסגה היא סכום הקומה השנייה. מה ?"
  - "בגלגל מספרים: בלב 6, בחישורים ?, כאשר כל חישור + 6 = 12. מצא ?"
  - "במשולש: שני מספרים בתחתית 11 ו-?. המספר באמצע הצלע הוא ההפרש שלהם. הפסגה סכום האמצע והתחתון הגבוה. אם הפסגה 15, מה ?"
  - "בלוח 3×3: על האלכסון 2, ?, ?,  בסדר. סכום האלכסון 18. מצא ?"
  - "ביהלום מספרים: צמד אופקי 7 ו-?. צמד אנכי 9 ו-?. סכומי האלכסונים 16. מצא ?"
  - "בטבלה 2×2: ההפרש בכל שורה 3 והפרש בכל עמודה 5. פינה עליונה שמאל 4. מצא יתר הפינות."
  - "בשרשרת 4 מספרים: כל מספר שני הוא כפול הקודם. מתחילים 3, ?‎,?, ?. מצא ?"
  - "במשולש הפוך: הבסיס ?, 5. האמצע מעליהם הוא המכפלה. הפסגה סכום של האמצע ו-3. אם הפסגה 28, מה ?"
  - "בטבלת 2×3: המכפלה בכל שורה 96. שורה ראשונה 6, ?, ?. שורה שנייה ?, ?, 4. מצא ?"
  - "במתומן: שני מספרים ממול שונים ב-6. אם צד אחד 9, מה הצד שמולו?"
  - "בשרשרת 5 מספרים: כל מספר רביעי הוא סכום של הראשון והשני. אם 2, 4, ?, ?, ?. מצא ?"
  - "בבית עם עליית גג: הקיר השמאלי 8, הימני ?, הגג סכום הקירות. אם הוסיפו חלון שערכו 3 פחות מהגג, מה ?"
  - "במגדל 3 קומות: קומה תחתונה 7, ?. קומה אמצע ?, פסגה ?. כל קומה היא סכום השניים שמתחתיה. מצא ?"
  - "בטבלה 3×1: 5, ?, 20. כל מספר אמצעי הוא מחצית הסכום של השכנים. מצא ?"
  - "במשולש מספרים: על צלע ימין 8 ו-?. אמצע הצלע שווה 9. מה ?"
  - "בלוח 2×2: המכפלה באלכסון הראשי 72 ובאלכסון המשני 90. האלכסון הראשי 6 ו-?, והשני 10 ו-?. מצא ?"
