game:
  type: "multiple_choice"
  name: "אוצר מילים למתקדמים"
  description: "הרחבת אוצר המילים בעברית"
  showTimer: false
  categories:
    Hebrew_Advanced_Vocabulary:
      name: "מילים למתקדמים"
  multipleChoice:
    enabled: false
    checked: true
    choiceCount: 4
  scoring:
    trackTime: true
    trackAccuracy: true
  exerciseCount: 50
  content:
    - answer: "מְנוֹרָה"
      choices:
        - "מַפָּה"
        - "וִילוֹן"
        - "מִטְרִיָה"
      question: "נִבְרֶשֶׁת"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "מַרְאָה"
      choices:
        - "מַצְלֵמָה"
        - "חַלּוֹן"
        - "מִסְגֶרֶת"
      question: "אַסְפַּקְלַרְיָה"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "בֵּין-עַרְבַּיִם"
      choices:
        - "זְרִיחָה"
        - "חֲצוֹת"
        - "בֹּקֶר"
      question: "דִמְדּוּמִים"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "מַטֶה"
      choices:
        - "כֶּתֶר"
        - "חֶרֶב"
        - "מָגֵן"
      question: "שַׁרְבִיט"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "קְלָף"
      choices:
        - "סֵפֶר"
        - "מַחְבֶּרֶת"
        - "עִתּוֹן"
      question: "מְגִילָּה"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "צֵל"
      choices:
        - "אוֹר"
        - "נֵר"
        - "לַפִּיד"
      question: "אָהִיל"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "מָעוֹז"
      choices:
        - "בַּיִת"
        - "גָּדֵר"
        - "שַׁעַר"
      question: "מִבְצָר"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "נַרְתִּיק"
      choices:
        - "קַסְדָּה"
        - "כְּפָפָה"
        - "אַרְנָק"
      question: "נָדָן"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "חַלּוֹן"
      choices:
        - "דֶלֶת"
        - "קִיר"
        - "גַּג"
      question: "אֶשְׁנָב"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "עֵץ"
      choices:
        - "פֶּרַח"
        - "שִׂיחַ"
        - "דֶשֶׁא"
      question: "אִילָן"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "מַתָּנָה"
      choices:
        - "בַּקָשָׁה"
        - "הַצָּעָה"
        - "מִכְתָּב"
      question: "תְּשׁוּרָה"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "זֶמֶר"
      choices:
        - "רִקוּד"
        - "צִיּוּר"
        - "סִפּוּר"
      question: "פִּזְמוֹן"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "סִפּוּר"
      choices:
        - "שְׁאֵלָה"
        - "תְּשׁוּבָה"
        - "בְּדִיחָה"
      question: "עֲלִילָה"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "זְרִיחָה"
      choices:
        - "שְׁקִיעָה"
        - "עֶרֶב"
        - "לַיְלָה"
      question: "שַׁחַר"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "הַד"
      choices:
        - "רַעַשׁ"
        - "קוֹל"
        - "צְעָקָה"
      question: "בַּת-קוֹל"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "שֶׁקֶט"
      choices:
        - "סְעָרָה"
        - "מְהוּמָה"
        - "צְפִירָה"
      question: "דּוּמִיָה"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "דִמְיוֹן"
      choices:
        - "מְצִיאוּת"
        - "אֱמֶת"
        - "עוּבְדָה"
      question: "אַשְׁלָיָה"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "חֹם"
      choices:
        - "קֹר"
        - "רוּחַ"
        - "גֶשֶׁם"
      question: "שָׁרָב"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "עוֹלָם"
      choices:
        - "רֶגַע"
        - "שָׁנָה"
        - "יוֹם"
      question: "נֶצַח"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "קו"
      choices:
        - "עִגוּל"
        - "רִבּוּעַ"
        - "מְשׁוּלָשׁ"
      question: "אֹפֶק"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "רְסִיסֵי-לַיְלָה"
      choices:
        - "עֲנָנִים"
        - "בָּרָד"
        - "שֶׁלֶג"
      question: "טַל"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "עָנָן"
      choices:
        - "אובֶך"
        - "עָשָׁן"
        - "קִיטוֹר"
      question: "עֲרָפֶל"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "סְחַרְחוֹרֶת"
      choices:
        - "נָהָר"
        - "אֲגַם"
        - "גַּל"
      question: "מַעֲרְבֹּלֶת"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "צֶמַח"
      choices:
        - "עָנָף"
        - "שֹׁרֶשׁ"
        - "גֶזַע"
      question: "נֶבֶט"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "זֶרַע"
      choices:
        - "פְּרִי"
        - "יָרָק"
        - "עָלֶה"
      question: "אַבְקָה"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "אֶבֶן"
      choices:
        - "חוֹל"
        - "עֵץ"
        - "בַּרְזֶל"
      question: "נָטִיף"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "דְבָרִים"
      choices:
        - "צְעָקוֹת"
        - "שִׁירים"
        - "תְּפִלּוֹת"
      question: "לְחִישָׁה"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "רִיצָה"
      choices:
        - "הֲלִיכָה"
        - "קְפִיצָה"
        - "זְחִילָה"
      question: "דְהָרָה"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "מַבָּט"
      choices:
        - "הַקְשָׁבָה"
        - "הֲרָחָה"
        - "טְעִימָה"
      question: "הֲצָצָה"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "יָשָׁן"
      choices:
        - "חָדָשׁ"
        - "צָעִיר"
        - "גָּדוֹל"
      question: "עַתִּיק"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "עָצוּם"
      choices:
        - "קָטָן"
        - "בֵּינוֹנִי"
        - "אָרֹךְ"
      question: "כַּבִּיר"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "נוֹצֵץ"
      choices:
        - "כֵּהֶה"
        - "מַט"
        - "עָכוּר"
      question: "זוֹהֵר"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "מַרְאֶה"
      choices:
        - "אָטוּם"
        - "עָבֶה"
        - "קָשֶׁה"
      question: "שָׁקוּף"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "עָצוּב"
      choices:
        - "שָׂמֵחַ"
        - "מָתוֹק"
        - "בָּהִיר"
      question: "קוֹדֵר"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "מָהִיר"
      choices:
        - "אִטִי"
        - "חַלָשׁ"
        - "כָּבֵד"
      question: "זָרִיז"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "נציג"
      choices:
        - "מֶלֶךְ"
        - "שַׂר"
        - "שׁוֹפֵט"
      question: "שָׁלִיחַ"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "מַמְשִׁיךְ"
      choices:
        - "מַתְחִיל"
        - "מְסַיֵם"
        - "עוֹצֵר"
      question: "יוֹרֵשׁ"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "גִבּוֹר"
      choices:
        - "פַּחְדָן"
        - "עָצֵל"
        - "רָשָׁע"
      question: "אַבִּיר"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "יוֹצֵר"
      choices:
        - "מוֹכֵר"
        - "קוֹנֶה"
        - "הוֹרֵס"
      question: "אֻמָּן"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "סַיָר"
      choices:
        - "טַיָס"
        - "מַלָח"
        - "נֶהָג"
      question: "צَوْפֶה"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "יָרֵחַ"
      choices:
        - "שֶׁמֶשׁ"
        - "כּוֹכָב"
        - "עָנָן"
      question: "סַהַר"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "שֶׁמֶשׁ"
      choices:
        - "יָרֵחַ"
        - "אֲדָמָה"
        - "שָׁמַיִם"
      question: "חַמָּה"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "כְּמִין-מִלְכֹּדֶת"
      choices:
        - "מִשְׂחָק"
        - "מְסִבָּה"
        - "הַפְתָּעָה"
      question: "מַאֲרָב"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "קֶסֶם"
      choices:
        - "פֶּלֶא"
        - "כֹּחַ"
        - "חָכְמָה"
      question: "מִקְסָם"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "בֶּגֶד"
      choices:
        - "נַעַל"
        - "כּוֹבַע"
        - "גַרְבַּיִם"
      question: "צָעִיף"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "שְׁבִיל"
      choices:
        - "כְּבִישׁ"
        - "מִדְרָכָה"
        - "גֶשֶׁר"
      question: "מִשְׁעוֹל"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "טִפָּה"
      choices:
        - "שֶׁלֶג"
        - "קֶרַח"
        - "אֵד"
      question: "אֵגֶל"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "פֶּחָם"
      choices:
        - "אֵשׁ"
        - "עָשָׁן"
        - "אֵפֶר"
      question: "גַחֶלֶת"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "עָנָף"
      choices:
        - "שֹׁרֶשׁ"
        - "גֶזַע"
        - "קְלִפָּה"
      question: "זַלְזַל"
      category: "Hebrew_Advanced_Vocabulary"
    - answer: "בַּת-צְחוֹק"
      choices:
        - "בֶּכִי"
        - "כַּעַס"
        - "פַּחַד"
      question: "חִיּוּךְ"
      category: "Hebrew_Advanced_Vocabulary"