game:
  type: "language"
  name: "אנגלית"
  description: "תרגול אנגלית"
  showTimer: true
  categories:
    animals:
      name: "חיות"
      enabled: true
    colors:
      name: "צבעים"
      enabled: true
    numbers:
      name: "מספרים"
      enabled: true
    family:
      name: "משפחה"
      enabled: true
    food:
      name: "אוכל"
      enabled: true
  exerciseCount: 30
  # Grid dimensions for the overlay (rows x cols)
  grid:
    rows: 5
    cols: 6
  multipleChoice:
    enabled: true
    checked: true
    choiceCount: 4
  scoring:
    trackTime: true
    trackAccuracy: true
  content:
    # Animals
    - hebrew: "כלב"
      english: "dog"
      category: "animals"
    - hebrew: "חתול"
      english: "cat"
      category: "animals"
    - hebrew: "סוס"
      english: "horse"
      category: "animals"
    - hebrew: "פרה"
      english: "cow"
      category: "animals"
    - hebrew: "ציפור"
      english: "bird"
      category: "animals"
    - hebrew: "דג"
      english: "fish"
      category: "animals"
    - hebrew: "אריה"
      english: "lion"
      category: "animals"
    - hebrew: "נמר"
      english: "tiger"
      category: "animals"
    - hebrew: "פיל"
      english: "elephant"
      category: "animals"
    - hebrew: "ג'ירפה"
      english: "giraffe"
      category: "animals"
    - hebrew: "שועל"
      english: "fox"
      category: "animals"
    - hebrew: "זאב"
      english: "wolf"
      category: "animals"
    - hebrew: "כבשה"
      english: "sheep"
      category: "animals"
    - hebrew: "עז"
      english: "goat"
      category: "animals"
    - hebrew: "תרנגול"
      english: "rooster"
      category: "animals"
    - hebrew: "תרנגולת"
      english: "hen"
      category: "animals"
    - hebrew: "ברווז"
      english: "duck"
      category: "animals"
    - hebrew: "חמור"
      english: "donkey"
      category: "animals"
    - hebrew: "עכבר"
      english: "mouse"
      category: "animals"
    - hebrew: "חולדה"
      english: "rat"
      category: "animals"
    - hebrew: "תיש"
      english: "buck"
      category: "animals"
    - hebrew: "גמל"
      english: "camel"
      category: "animals"
    - hebrew: "תן"
      english: "jackal"
      category: "animals"
    - hebrew: "צב"
      english: "turtle"
      category: "animals"
    - hebrew: "לטאה"
      english: "lizard"
      category: "animals"
    - hebrew: "נחש"
      english: "snake"
      category: "animals"
    - hebrew: "עורב"
      english: "crow"
      category: "animals"
    - hebrew: "יונה"
      english: "dove"
      category: "animals"
    - hebrew: "תוכי"
      english: "parrot"
      category: "animals"
    - hebrew: "פרפר"
      english: "butterfly"
      category: "animals"
    # Colors
    - hebrew: "אדום"
      english: "red"
      category: "colors"
    - hebrew: "כחול"
      english: "blue"
      category: "colors"
    - hebrew: "ירוק"
      english: "green"
      category: "colors"
    - hebrew: "צהוב"
      english: "yellow"
      category: "colors"
    - hebrew: "שחור"
      english: "black"
      category: "colors"
    - hebrew: "לבן"
      english: "white"
      category: "colors"
    - hebrew: "כתום"
      english: "orange"
      category: "colors"
    - hebrew: "סגול"
      english: "purple"
      category: "colors"
    - hebrew: "ורוד"
      english: "pink"
      category: "colors"
    - hebrew: "חום"
      english: "brown"
      category: "colors"
    - hebrew: "אפור"
      english: "gray"
      category: "colors"
    - hebrew: "טורקיז"
      english: "turquoise"
      category: "colors"
    - hebrew: "זהב"
      english: "gold"
      category: "colors"
    - hebrew: "כסף"
      english: "silver"
      category: "colors"
    - hebrew: "בורדו"
      english: "burgundy"
      category: "colors"
    - hebrew: "תכלת"
      english: "sky blue"
      category: "colors"
    - hebrew: "זית"
      english: "olive"
      category: "colors"
    - hebrew: "קרם"
      english: "cream"
      category: "colors"
    - hebrew: "מנטה"
      english: "mint"
      category: "colors"
    - hebrew: "חציל"
      english: "eggplant"
      category: "colors"
    # Numbers
    - hebrew: "אחד"
      english: "one"
      category: "numbers"
    - hebrew: "שתיים"
      english: "two"
      category: "numbers"
    - hebrew: "שלוש"
      english: "three"
      category: "numbers"
    - hebrew: "ארבע"
      english: "four"
      category: "numbers"
    - hebrew: "חמש"
      english: "five"
      category: "numbers"
    - hebrew: "שש"
      english: "six"
      category: "numbers"
    - hebrew: "שבע"
      english: "seven"
      category: "numbers"
    - hebrew: "שמונה"
      english: "eight"
      category: "numbers"
    - hebrew: "תשע"
      english: "nine"
      category: "numbers"
    - hebrew: "עשר"
      english: "ten"
      category: "numbers"
    - hebrew: "אחת עשרה"
      english: "eleven"
      category: "numbers"
    - hebrew: "שתים עשרה"
      english: "twelve"
      category: "numbers"
    - hebrew: "שלוש עשרה"
      english: "thirteen"
      category: "numbers"
    - hebrew: "ארבע עשרה"
      english: "fourteen"
      category: "numbers"
    - hebrew: "חמש עשרה"
      english: "fifteen"
      category: "numbers"
    - hebrew: "עשרים"
      english: "twenty"
      category: "numbers"
    - hebrew: "שלושים"
      english: "thirty"
      category: "numbers"
    - hebrew: "ארבעים"
      english: "forty"
      category: "numbers"
    - hebrew: "חמישים"
      english: "fifty"
      category: "numbers"
    - hebrew: "מאה"
      english: "hundred"
      category: "numbers"
    # Family
    - hebrew: "אבא"
      english: "father"
      category: "family"
    - hebrew: "אמא"
      english: "mother"
      category: "family"
    - hebrew: "אח"
      english: "brother"
      category: "family"
    - hebrew: "אחות"
      english: "sister"
      category: "family"
    - hebrew: "סבא"
      english: "grandfather"
      category: "family"
    - hebrew: "סבתא"
      english: "grandmother"
      category: "family"
    - hebrew: "בן"
      english: "son"
      category: "family"
    - hebrew: "בת"
      english: "daughter"
      category: "family"
    - hebrew: "דוד"
      english: "uncle"
      category: "family"
    - hebrew: "דודה"
      english: "aunt"
      category: "family"
    - hebrew: "נכד"
      english: "grandson"
      category: "family"
    - hebrew: "נכדה"
      english: "granddaughter"
      category: "family"
    - hebrew: "אחיין"
      english: "nephew"
      category: "family"
    - hebrew: "אחיינית"
      english: "niece"
      category: "family"
    - hebrew: "גיס"
      english: "brother-in-law"
      category: "family"
    - hebrew: "גיסה"
      english: "sister-in-law"
      category: "family"
    - hebrew: "חם"
      english: "father-in-law"
      category: "family"
    - hebrew: "חמות"
      english: "mother-in-law"
      category: "family"
    - hebrew: "חתן"
      english: "son-in-law"
      category: "family"
    - hebrew: "כלה"
      english: "daughter-in-law"
      category: "family"
    # Food
    - hebrew: "לחם"
      english: "bread"
      category: "food"
    - hebrew: "חלב"
      english: "milk"
      category: "food"
    - hebrew: "תפוח"
      english: "apple"
      category: "food"
    - hebrew: "בננה"
      english: "banana"
      category: "food"
    - hebrew: "עוגה"
      english: "cake"
      category: "food"
    - hebrew: "ביצה"
      english: "egg"
      category: "food"
    - hebrew: "גבינה"
      english: "cheese"
      category: "food"
    - hebrew: "עוף"
      english: "chicken"
      category: "food"
    - hebrew: "אורז"
      english: "rice"
      category: "food"
    - hebrew: "פסטה"
      english: "pasta"
      category: "food"
    - hebrew: "מרק"
      english: "soup"
      category: "food"
    - hebrew: "שוקולד"
      english: "chocolate"
      category: "food"
    - hebrew: "מלפפון"
      english: "cucumber"
      category: "food"
    - hebrew: "עגבניה"
      english: "tomato"
      category: "food"
    - hebrew: "גזר"
      english: "carrot"
      category: "food"
    - hebrew: "בצל"
      english: "onion"
      category: "food"
    - hebrew: "מלח"
      english: "salt"
      category: "food"
    - hebrew: "סוכר"
      english: "sugar"
      category: "food"
    - hebrew: "דבש"
      english: "honey"
      category: "food"
    - hebrew: "מים"
      english: "water"
      category: "food" 