game:
  type: "language"
  name: "משחק שפה"
  description: "תרגול אנגלית"
  showTimer: true
  categories:
    animals:
      name: "חיות"
      enabled: true
    colors:
      name: "צבעים"
      enabled: true
    numbers:
      name: "מספרים"
      enabled: true
    family:
      name: "משפחה"
      enabled: true
    food:
      name: "אוכל"
      enabled: true
  exerciseCount: 15
  # Grid dimensions for the overlay (rows x cols)
  grid:
    rows: 4
    cols: 5
  multipleChoice:
    enabled: true
    checked: true
    choiceCount: 4
  scoring:
    trackTime: true
    trackAccuracy: true
  content:
    # Animals
    - hebrew: "כלב"
      english: "dog"
      category: "animals"
      audio: "audio/animals/dog.mp3"
      image: "images/animals/dog.jpg"
    - hebrew: "חתול"
      english: "cat"
      category: "animals"
      audio: "audio/animals/cat.mp3"
      image: "images/animals/cat.jpg"
    - hebrew: "סוס"
      english: "horse"
      category: "animals"
      audio: "audio/animals/horse.mp3"
      image: "images/animals/horse.jpg"
    - hebrew: "פרה"
      english: "cow"
      category: "animals"
      audio: "audio/animals/cow.mp3"
      image: "images/animals/cow.jpg"
    - hebrew: "ציפור"
      english: "bird"
      category: "animals"
      audio: "audio/animals/bird.mp3"
      image: "images/animals/bird.jpg"
    
    # Colors
    - hebrew: "אדום"
      english: "red"
      category: "colors"
      audio: "audio/colors/red.mp3"
      image: "images/colors/red.jpg"
    - hebrew: "כחול"
      english: "blue"
      category: "colors"
      audio: "audio/colors/blue.mp3"
      image: "images/colors/blue.jpg"
    - hebrew: "ירוק"
      english: "green"
      category: "colors"
      audio: "audio/colors/green.mp3"
      image: "images/colors/green.jpg"
    - hebrew: "צהוב"
      english: "yellow"
      category: "colors"
      audio: "audio/colors/yellow.mp3"
      image: "images/colors/yellow.jpg"
    - hebrew: "שחור"
      english: "black"
      category: "colors"
      audio: "audio/colors/black.mp3"
      image: "images/colors/black.jpg"
    
    # Numbers
    - hebrew: "אחד"
      english: "one"
      category: "numbers"
      audio: "audio/numbers/one.mp3"
      image: "images/numbers/1.jpg"
    - hebrew: "שתיים"
      english: "two"
      category: "numbers"
      audio: "audio/numbers/two.mp3"
      image: "images/numbers/2.jpg"
    - hebrew: "שלוש"
      english: "three"
      category: "numbers"
      audio: "audio/numbers/three.mp3"
      image: "images/numbers/3.jpg"
    - hebrew: "ארבע"
      english: "four"
      category: "numbers"
      audio: "audio/numbers/four.mp3"
      image: "images/numbers/4.jpg"
    - hebrew: "חמש"
      english: "five"
      category: "numbers"
      audio: "audio/numbers/five.mp3"
      image: "images/numbers/5.jpg"
    
    # Family
    - hebrew: "אבא"
      english: "father"
      category: "family"
      audio: "audio/family/father.mp3"
      image: "images/family/father.jpg"
    - hebrew: "אמא"
      english: "mother"
      category: "family"
      audio: "audio/family/mother.mp3"
      image: "images/family/mother.jpg"
    - hebrew: "אח"
      english: "brother"
      category: "family"
      audio: "audio/family/brother.mp3"
      image: "images/family/brother.jpg"
    - hebrew: "אחות"
      english: "sister"
      category: "family"
      audio: "audio/family/sister.mp3"
      image: "images/family/sister.jpg"
    - hebrew: "סבא"
      english: "grandfather"
      category: "family"
      audio: "audio/family/grandfather.mp3"
      image: "images/family/grandfather.jpg"
    
    # Food
    - hebrew: "לחם"
      english: "bread"
      category: "food"
      audio: "audio/food/bread.mp3"
      image: "images/food/bread.jpg"
    - hebrew: "חלב"
      english: "milk"
      category: "food"
      audio: "audio/food/milk.mp3"
      image: "images/food/milk.jpg"
    - hebrew: "תפוח"
      english: "apple"
      category: "food"
      audio: "audio/food/apple.mp3"
      image: "images/food/apple.jpg"
    - hebrew: "בננה"
      english: "banana"
      category: "food"
      audio: "audio/food/banana.mp3"
      image: "images/food/banana.jpg"
    - hebrew: "עוגה"
      english: "cake"
      category: "food"
      audio: "audio/food/cake.mp3"
      image: "images/food/cake.jpg" 