game:
  type: "math"
  name: "משחק זיכרון מתמטי"
  description: "תרגול פעולות חשבון"
  showTimer: true
  operations:
    addition:
      symbol: "+"
      name: "חיבור"
      enabled: true
    subtraction:
      symbol: "-"
      name: "חיסור"
      enabled: true
    multiplication:
      symbol: "×"
      name: "כפל"
      enabled: false
    division:
      symbol: "/"
      name: "חילוק"
      enabled: false
  numberRange:
    min: 1
    max: 20
  exerciseCount: 20
  multipleChoice:
    enabled: true
    checked: false
    choiceCount: 4
    constraints:
      nonNegative: true
      maxValue: 400
  scoring:
    trackTime: true
    trackAccuracy: true 