game:
  type: "math"
  name: "חשבון"
  description: "תרגול פעולות חשבון"
  showTimer: true
  operations:
    addition:
      symbol: "+"
      name: "חיבור"
      enabled: true
    subtraction:
      symbol: "-"
      name: "חיסור"
      enabled: true
    multiplication:
      symbol: "×"
      name: "כפל"
      enabled: false
    division:
      symbol: "/"
      name: "חילוק"
      enabled: false
  numberRange:
    min: 1
    max: 20
  exerciseCount: 30
  # Grid dimensions for the overlay (rows x cols)
  grid:
    rows: 5
    cols: 6
  multipleChoice:
    enabled: true
    checked: false
    choiceCount: 4
    constraints:
      nonNegative: true
      maxValue: 400
  scoring:
    trackTime: true
    trackAccuracy: true 
  instructions: |
    ### איך משחקים?
    1. בחר את סוגי הפעולות שברצונך לתרגל (חיבור, חיסור, כפל, חילוק)
    2. בחר את המספרים שברצונך לתרגל (1-20)
    3. לחץ על "התחל משחק"
    4. כאשר מופיע תרגיל:
       - אמור את התשובה בקול רם
       - לחץ על מקש הרווח כדי לעבור לתרגיל הבא
    5. ככל שתפתור יותר תרגילים, תמונה של דמות דיסני תתגלה בהדרגה
    6. לאחר 20 תרגילים, המשחק יסתיים ותוכל לראות את הסטטיסטיקות שלך

    ### טיפים להורים:
    - התחל עם מספרים קטנים ופחות אפשרויות כדי לבנות ביטחון
    - הגדל בהדרגה את הקושי על ידי הוספת מספרים
    - השתמש במשחק כדרך מהנה לתרגל עובדות מתמטיות
    - עודד את הילד לומר את התשובה בקול רם לפני לחיצה על מקש הרווח
    - חגגו את ההתקדמות והשלמת כל משחק 